/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.github.lanchonete.view;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.java.com.github.Lanchonete.model.Cozinha;
import main.java.com.github.Lanchonete.model.Pedido;
import main.java.com.github.lanchonete.controller.CadastrarPedidosArquivo;
import main.java.com.github.lanchonete.model.TabelaPedido;

/**
 *
 * @author Diones Gomes
 */
public class AtenderPedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
    CadastrarPedidosArquivo cad = new CadastrarPedidosArquivo();
    TabelaPedido tab = new TabelaPedido();

    public AtenderPedidos() {
        initComponents();
        incializarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AtenderPedido = new javax.swing.JTable();
        jButtonAtender = new javax.swing.JButton();
        ModificarPedido = new javax.swing.JButton();
        ExcluirPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos");
        setResizable(false);

        AtenderPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Mesa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AtenderPedido);

        jButtonAtender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonAtender.setText("Atender ");
        jButtonAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtenderActionPerformed(evt);
            }
        });

        ModificarPedido.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ModificarPedido.setText("Modificar");
        ModificarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPedidoActionPerformed(evt);
            }
        });

        ExcluirPedido.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ExcluirPedido.setText("Excluir");
        ExcluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtender, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExcluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAtender, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(ModificarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExcluirPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPedidoActionPerformed
        // TODO add your handling code here:
        int linha = AtenderPedido.getSelectedRow();
        Object mesa = AtenderPedido.getValueAt(linha, 2);
        int numMesa = Integer.parseInt(mesa.toString());

        new EditarPedido(numMesa).setVisible(true);
        dispose();
    }//GEN-LAST:event_ModificarPedidoActionPerformed

    private void jButtonAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtenderActionPerformed
        try {
            // TODO add your handling code here:
            atender();
        } catch (IOException ex) {
            Logger.getLogger(AtenderPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AtenderPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAtenderActionPerformed

    private void ExcluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirPedidoActionPerformed
        deletar();
    }//GEN-LAST:event_ExcluirPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AtenderPedido;
    private javax.swing.JButton ExcluirPedido;
    private javax.swing.JButton ModificarPedido;
    private javax.swing.JButton jButtonAtender;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
     private void incializarTabela() {
        try {
            List<Pedido> lista = null;

            lista = cad.listar();

            tab.addList(lista);
            AtenderPedido.setModel(tab);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Falha na conexão com arquivo",
                    "Mensagem Erro", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void deletar() {
        int linha = AtenderPedido.getSelectedRow();

        if (linha >= 0) {

            try {

                Object numeroPedido = AtenderPedido.getValueAt(linha, 3);
                Object mesa = AtenderPedido.getValueAt(linha, 2);
                int numPedido = Integer.parseInt(numeroPedido.toString());
                int numMesa = Integer.parseInt(mesa.toString());

                cad.deletar(numMesa, numPedido);
                incializarTabela();

            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(ExluirContas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void atender() throws IOException, ClassNotFoundException {

        int linha = AtenderPedido.getSelectedRow();
        Object numeroPedido = AtenderPedido.getValueAt(linha, 3);
        Object mesa = AtenderPedido.getValueAt(linha, 2);
        int numPedido = Integer.parseInt(numeroPedido.toString());
        int numMesa = Integer.parseInt(mesa.toString());

        cad.mudarStatus(numPedido, numMesa);
        incializarTabela();
    }
}
