
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.github.lanchonete.view;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.java.com.github.Lanchonete.model.Produto;
import main.java.com.github.lanchonete.controller.CadastrarProdutoArquivo;
import main.java.com.github.lanchonete.model.TabelaProduto;
import main.java.com.github.Lanchonete.controller.GerenciaMesa;
import main.java.com.github.Lanchonete.model.Pedido;
import main.java.com.github.lanchonete.controller.CadastrarPedidosArquivo;
import main.java.com.github.lanchonete.controller.GerenciaMenu;

/**
 *
 * @author Diones Gomes
 */
public class TelaFazerPedido extends javax.swing.JFrame {

    /**
     * Creates new form Pedido
     */
    public CadastrarProdutoArquivo cad = new CadastrarProdutoArquivo();
    public TabelaProduto tabela = new TabelaProduto();
    public GerenciaMesa gm = new GerenciaMesa();
    private int codProduto;
    private  int quantidade;

    public TelaFazerPedido() {
        initComponents();
        incializarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FazerPedido = new javax.swing.JButton();
        QuantidadePedido = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tableproduct = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fazer Pedidos ");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Produtos");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Quantidade");

        FazerPedido.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FazerPedido.setText("Pedir");
        FazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FazerPedidoActionPerformed(evt);
            }
        });

        QuantidadePedido.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        Tableproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descrição", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tableproduct);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(FazerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(QuantidadePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(QuantidadePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(FazerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void FazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FazerPedidoActionPerformed
        
        try {
            pedir();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(TelaFazerPedido.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_FazerPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FazerPedido;
    private javax.swing.JSpinner QuantidadePedido;
    private javax.swing.JTable Tableproduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void incializarTabela() {
        try {
            List<Produto> lista = null;

            lista = cad.listar();

            tabela.addList(lista);
            Tableproduct.setModel(tabela);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Falha na conexão com arquivo",
                    "Mensagem Erro", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void pedir() throws IOException, ClassNotFoundException {
        int linha = Tableproduct.getSelectedRow();

        if (linha >= 0) {

            Object codigo = Tableproduct.getValueAt(linha, 0);
            codProduto = Integer.parseInt(codigo.toString());
            quantidade = (int) QuantidadePedido.getValue(); 
            
            Pedido p = new Pedido(GerenciaMenu.EscolherProduto(codProduto),quantidade);
            p.setMesa(TelaGerenciarMesa.getMesa());
            CadastrarPedidosArquivo cad = new CadastrarPedidosArquivo();
            
            
            
            
            if(cad.Adicionar(p)) {
            
                JOptionPane.showMessageDialog(null, "Pedido realizado com sucesso!");
                
            } else {
                JOptionPane.showMessageDialog(null, "Pedido não foi efetuado!");                
                JOptionPane.showMessageDialog(null, "Númeor da mesa"+TelaGerenciarMesa.getMesa());
                JOptionPane.showMessageDialog(null, "Código produto"+codProduto);
                JOptionPane.showMessageDialog(null, "Quantidade do produto"+quantidade);
            }
             incializarTabela();         
        }
    }

}
