/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Setor;
import model.Usuario;
import controller.UsuariosArquivoDAO;
import exceptions.CpfExcecption;
import exceptions.FormularioException;
import exceptions.TelefoneException;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Diones Gomes
 */
public class TelaEditarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form TelaEditarUsuarios
     */
    private String email;

    public TelaEditarUsuarios() {
        initComponents();
    }

    TelaEditarUsuarios(String email) {
        this.email = email;
        initComponents();
        preencherCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Atualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        telefone = new javax.swing.JFormattedTextField();
        nascimento = new javax.swing.JFormattedTextField();
        setor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Usuários");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Atualizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        jPanel2.add(Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 135, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 421, -1, -1));

        jButtonCancelar1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonCancelar1.setText("Cancelar");
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 120, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("CPF");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 13, -1, -1));

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        jPanel2.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 11, 265, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nome");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 52, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("E-Mail");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 103, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Telefone");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 185, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Nascimeto");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 247, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Setor");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel2.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 52, 265, 31));
        jPanel2.add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 101, 265, 31));

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        jPanel2.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 183, 265, 31));

        try {
            nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 245, 265, 31));

        setor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        setor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendimento", "Cozinha", "Caixa", "Gerencia" }));
        jPanel2.add(setor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 265, 33));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Senha");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 143, -1, -1));

        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        jPanel2.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 143, 265, 27));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 26, 520, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        try {
            verificarCampos();
            atualizarDados();
        }catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(null, "Preencha a data de Nascimento");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaEditarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CpfExcecption ex) {
            JOptionPane.showMessageDialog(null, "Preencha o CPF");
        } catch (TelefoneException ex) {
            JOptionPane.showMessageDialog(null, "Preencha o TELEFONE");
        } catch (FormularioException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Mensagem de Erro", JOptionPane.ERROR_MESSAGE);
        }catch (IOException ex) {
            Logger.getLogger(TelaEditarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } 

    }//GEN-LAST:event_AtualizarActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField nascimento;
    private javax.swing.JTextField nome;
    private javax.swing.JPasswordField senha;
    private javax.swing.JComboBox<String> setor;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JTextField textEmail;
    // End of variables declaration//GEN-END:variables

    private void preencherCampos() {

        UsuariosArquivoDAO cad = new UsuariosArquivoDAO();
        Usuario usuario;
        try {

            usuario = cad.buscar(email);
            cpf.setText(usuario.getCpf());
            nome.setText(usuario.getNome());
            textEmail.setText(usuario.getEmail());
            telefone.setText(usuario.getTelefone());
            senha.setText(usuario.getSenha());

            LocalDate nas = usuario.getNascimento();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String dnascimento = nas.format(formatter);
            nascimento.setText(dnascimento);

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(TelaEditarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void atualizarDados() throws IOException, FileNotFoundException, ClassNotFoundException, CpfExcecption, TelefoneException, FormularioException {
        verificarCampos();
        String vcpf = cpf.getText();
        String vemail = textEmail.getText();
        String vsenha = new String(senha.getPassword());
        String vnome = nome.getText();
        String vtelefone = telefone.getText();
        int vsetor = setor.getSelectedIndex();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String vnascimento = nascimento.getText();
        LocalDate datanascimento = LocalDate.parse(vnascimento, formato);

        Setor s = null;

        switch (vsetor) {
            case 0:
                s = Setor.GARCON;
                break;
            case 1:
                s = Setor.COZINHA;
                break;
            case 2:
                s = Setor.CAIXA;
                break;
            case 3:
                s = Setor.GERENCIA;
                break;
        }
        Usuario usuario = new Usuario(vcpf, vnome, vemail, vsenha, vtelefone, datanascimento, s);

        UsuariosArquivoDAO cad = new UsuariosArquivoDAO();
        if (cad.atualizar(email, usuario)) {
            JOptionPane.showMessageDialog(null, "Atualizado!");
        }
        this.dispose();
    }

    private void verificarCampos() throws FormularioException {

        if (nome.getText().equals("")) {
            throw new FormularioException("O campo NOME não pode estar vazio");
        }

        if (textEmail.getText().equals("")) {
            throw new FormularioException("O campo E-MAIL não pode estar vazio!");
        }

        if (String.copyValueOf(senha.getPassword()).equals("")) {
            throw new FormularioException("O campo SENHA não pode estar vazio!");
        }

    }

}
